Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -22,15 +22,15 @@ jobs:
       contents: read
     steps:
 
-      - name: Check commit message format
-        env:
-          SUBJECT: ${{ github.event.head_commit.message }}
-        run: |
-          SUBJECT="${SUBJECT%%$'\n'*}"
-          if ! echo "$SUBJECT" | grep -qE '^(feat|fix|docs|style|refactor|perf|test|chore)(\([a-z0-9-]+\))?: .+|^docs$|^Update \S+$'; then
-            echo "::error::Invalid commit message: $SUBJECT"
-            exit 1
-          fi
+      # - name: Check commit message format
+      #   env:
+      #     SUBJECT: ${{ github.event.head_commit.message }}
+      #   run: |
+      #     SUBJECT="${SUBJECT%%$'\n'*}"
+      #     if ! echo "$SUBJECT" | grep -qE '^(feat|fix|docs|style|refactor|perf|test|chore)(\([a-z0-9-]+\))?: .+|^docs$|^Update \S+$'; then
+      #       echo "::error::Invalid commit message: $SUBJECT"
+      #       exit 1
+      #     fi
 
       - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
         with:
